export const CARTMINI = 'cartMini'
export const CURRENCY = 'currency'
export const CATEGORY = 'category'
export const ALLCATEGORY = 'allCategory'
export const ALLCURRENCY = 'allCurrencies'
export const ADDTOCART = 'addToCart'
export const MUTATEQUANTITY = 'mutateQuantity'
export const DELETE_ITEM_IN_CART = 'deleteItemInCart'